#!/bin/bash
source /usr/local/bin/supervisor_drupal_helpers.sh

# $1 is absolute path to database dump, else project root path will be prepended
# $2 is name of the datbaase to populate
load(){
  db_dump="$1"
  db_name="$2"
  [[ $db_dump  =~ ^/ ]] || db_dump="${_conf_prj_root}/$db_dump"
  if [[ ! -f $db_dump ]]; then
    log "database dump '$db_dump' does not exist"
    exit 1
  fi
  log "loading database dump $db_dump into MySQL database $db_name ..."
  if gunzip -t "$db_dump" 2>/dev/null; then
    dump_length="$(zcat -l $db_dump | awk 'NR == 2 {print $2}')"
    cat='zcat'
  else
    dump_length="$( du -sh $db_dump  | cut -f1 )"
    cat='cat'
  fi
  mysql -u root -p"${_conf_db_root}" -e "DROP DATABASE IF EXISTS $db_name ; CREATE DATABASE IF NOT EXISTS $db_name";
  $cat "$db_dump" | pv --force --size $dump_length | mysql -u root -p"${_conf_db_root}" -D $db_name
}

supervisor_service_up mysql

load "$@"

supervisor_services_done
